/** Site chrome for the multi-page platform (home, services, developers, trust, about).
 *
 *  Rules (same as i18n.ts, checked by site.test.ts):
 *  - No religious text here. Ever. Quran/Hadith only ever comes from the API or a recorded API response.
 *  - The four states are NEVER re-worded here: pages call msg(lang, "labels", status) from messages/*.json.
 *  - No judgment vocabulary (the backend's forbidden lexicon is re-checked on these strings).
 *  - No numbers: every figure on the Trust page comes from __generated__/trust.json (scripts/gen_trust.py).
 *  - ar and en have identical key sets. */

import type { Lang } from "../api";

const ar = {
  // navigation
  nav_home: "الرئيسية",
  nav_check: "مساحة التحقق",
  nav_services: "الخدمات",
  nav_developers: "للمطورين",
  nav_trust: "لماذا تثق بنا",
  nav_about: "عن بصيرة",
  nav_menu: "القائمة",
  nav_close: "إغلاق القائمة",
  nav_primary: "التنقل الرئيسي",
  cta_start: "ابدأ التحقق",
  cta_try: "جرّب بنصّك",
  skip: "انتقل إلى المحتوى",
  badge_live: "يعمل الآن",
  badge_soon: "قريبًا",
  badge_soon_long: "قيد البناء — لا يعمل بعد",

  // identity
  identity: "طبقة الثقة للنص الشرعي في عصر الذكاء الاصطناعي",
  motto_ai: "الذكاء الاصطناعي يفهم",
  motto_engine: "والمحرك يتحقق",

  // hero
  hero_kicker: "تحقّق قبل أن تنشر",
  hero_title: "قبل أن ينتشر النص… تأكّد أنه نُقل بحرفه.",
  hero_sub:
    "الصق منشورًا أو ارفع صورته. تستخرج بصيرة كل آية وحديث، وتطابقها حرفًا بحرف مع المصدر، وتعرض نص المصدر بجانب نصك مع تظليل أي اختلاف.",
  hero_secondary: "كيف يعمل؟",
  demo_label: "عرض حيّ لفحص منشور",
  demo_caption_recorded: "استجابة مسجّلة حرفيًا من محرك بصيرة لهذا المنشور",
  demo_caption_live: "نتيجة حيّة الآن من المحرك",
  demo_post_title: "منشور قبل نشره",
  demo_replay: "أعد العرض",
  demo_run_live: "شغّله حيًا على المحرك",
  demo_running: "يفحص…",
  demo_your_word: "نصك",
  demo_source_word: "المصدر",
  demo_ai: "الذكاء الاصطناعي حدّد المواضع",
  demo_engine: "المحرك طابق حرفيًا",
  demo_ms: "{ms} م.ث",
  demo_quotes: "{n} اقتباسات",
  demo_open: "افتح هذا المثال في مساحة التحقق",
  demo_diff: "الفرق",

  // how it works
  how_title: "ثلاث خطوات. دور كل طرف واضح.",
  how_sub: "لا يكتب الذكاء الاصطناعي حرفًا من النص الشرعي. يحدّد المواضع فقط، ثم يتحقق محرك حتمي من كل حرف.",
  how_1_t: "تلصق أو ترفع",
  how_1_d: "منشور، رسالة، تعليق، أو صورة لمنشور. حتى ٥٠٠٠ حرف. لا نحفظ شيئًا.",
  how_2_t: "الذكاء الاصطناعي يفهم",
  how_2_d: "يقرأ النص أو الصورة ويحدّد أين تبدأ كل آية وكل حديث وأين تنتهي، ثم يُعاد تحديد كل موضع حرفيًا داخل نصك.",
  how_3_t: "المحرك يتحقق",
  how_3_d: "مطابقة حتمية مع مصادر مثبّتة بإصدارها وبصمتها: نفس النص يعطي نفس النتيجة دائمًا، ونص المصدر يُعرض كما هو.",
  how_role_ai: "دور الذكاء الاصطناعي",
  how_role_engine: "دور المحرك",

  // states
  states_title: "أربع حالات فقط. بلا أحكام.",
  states_sub: "بصيرة لا تُصدر حكمًا على أي نص. تقول أين وجدته في مصادرها، وكيف يختلف نصك عنه.",
  state_found_d: "نصك يطابق المصدر حرفيًا. نعرض موضعه ونصه.",
  state_partial_match_d: "قريب جدًا من حديث في مصادرنا؛ الكلمات المختلفة مظلّلة.",
  state_needs_review_d: "أي اختلاف عن نص المصحف، أو ما لا يكفي للحكم الآلي، يُحال إلى مراجعتك.",
  state_not_found_d: "معلومة عن نطاق مصادرنا، وليست حكمًا على النص.",

  // services
  services_title: "الخدمات",
  services_sub: "ما يعمل الآن يعمل فعلًا على المحرك. وما لم يُبنَ بعد معلَن بوضوح.",
  svc_text_t: "تحقق من نص عربي",
  svc_text_d: "الصق منشورًا كاملًا؛ يُستخرج كل اقتباس ويُطابق مع المصحف وكتب السنة التسعة.",
  svc_text_out: "تحصل على: الحالة لكل اقتباس، ونص المصدر، والفرق مظلّلًا، وروابط المراجع.",
  svc_image_t: "تحقق من صورة",
  svc_image_d: "ارفع لقطة المنشور؛ يُقرأ النص آليًا ويُعرض لك لتتأكد منه قبل الاعتماد على النتيجة.",
  svc_image_out: "تحصل على: النص المقروء من الصورة، ثم نفس فحص النص.",
  svc_en_t: "تحقق من اقتباس إنجليزي",
  svc_en_d: "يعيد الاقتباس المترجم إلى أصله العربي، ويعرض الترجمة المعتمدة من QuranEnc وHadeethEnc.",
  svc_en_out: "ستحصل على: الأصل العربي من المصدر + الترجمة المعتمدة منسوبة بإصدارها.",
  svc_guard_t: "الحارس",
  svc_guard_d: "افحص إجابة أي شات بوت إسلامي قبل أن تثق بها: كل آية وحديث في الإجابة يمرّ على المحرك.",
  svc_guard_out: "ستحصل على: تقرير لكل اقتباس في إجابة النموذج.",
  svc_api_t: "REST API و MCP Server",
  svc_api_d: "واجهة REST تعمل الآن. خادم MCP ليتحقق أي مساعد ذكي من اقتباساته قبل عرضها — قيد البناء.",
  svc_api_out: "تحصل على: نفس استجابة الواجهة بصيغة JSON موثّقة.",
  svc_receipt_t: "إيصال التحقق",
  svc_receipt_d: "بصمة ورمز QR يعيدان نفس النتيجة لأي شخص، دون أن نحفظ نصك.",
  svc_receipt_out: "ستحصل على: رابط/رمز يثبت ما فُحص ومتى وبأي إصدار من المصادر.",
  svc_trust_t: "لماذا تثق بنا",
  svc_trust_d: "الأرقام المقاسة ومنهجها ومصادرها، وصفحة «حدودنا» بما لا نغطيه.",
  svc_trust_out: "كل رقم بمصدره من تقارير المستودع.",
  svc_open: "افتح الخدمة",
  svc_learn: "التفاصيل",
  svc_for: "لمن؟",
  svc_audience: "للمعرّفين بالإسلام والدعاة وكل من ينشر محتوى دينيًا، بالعربية والإنجليزية.",

  // check page
  check_title: "مساحة التحقق",
  check_sub: "الصق النص أو ارفع صورة. النتيجة تظهر داخل نصك نفسه.",
  mode_text: "نص عربي",
  mode_image: "صورة",
  mode_en: "اقتباس إنجليزي",
  mode_guard: "الحارس",
  modes_label: "نوع الفحص",
  pipe_title: "ما الذي حدث في هذا الفحص",
  pipe_ai: "الذكاء الاصطناعي",
  pipe_ai_d: "حدّد مواضع الاقتباس",
  pipe_engine: "المحرك الحتمي",
  pipe_engine_d: "طابق حرفيًا مع المصادر",
  pipe_validator: "المدقّق اللاحق",
  pipe_validator_d: "ردود مرفوضة: {n}",
  pipe_corpus: "إصدارات المصادر",
  pipe_degraded: "القواعد الثابتة وحدها",
  receipt_soon: "إيصال التحقق (بصمة + QR)",
  soon_panel_en: "هذا الفحص قيد البناء. لن نعرض نتيجة لاقتباس إنجليزي قبل أن يعمل فعلًا على المحرك.",
  soon_panel_guard: "الحارس قيد البناء. حاليًا يمكنك لصق إجابة الشات بوت في «نص عربي» لفحص ما فيها من آيات وأحاديث.",
  go_text_mode: "انتقل إلى فحص النص",

  // developers
  dev_title: "للمطورين",
  dev_sub: "نفس المحرك الذي تستخدمه الواجهة، عبر واجهة REST موثّقة. بلا مفاتيح للفحص العام، مع حدّ للطلبات.",
  dev_quick: "ابدأ في دقيقة",
  dev_endpoints: "المسارات المتاحة الآن",
  dev_method: "الطريقة",
  dev_path: "المسار",
  dev_what: "الوظيفة",
  ep_health: "جاهزية الخادم وأعداد المدوّنة وإصداراتها",
  ep_check: "فحص نص (حتى ٥٠٠٠ حرف)",
  ep_image: "فحص صورة؛ يعيد النص المقروء أيضًا",
  ep_sources: "سجل المصادر: الإصدار والرخصة وعدد السجلات",
  ep_messages: "كل النصوص التي يراها المستخدم",
  ep_docs: "التوثيق التفاعلي (OpenAPI)",
  dev_contract: "عقد الاستجابة",
  dev_contract_d: "كل استجابة تحمل إصدارات المصادر، والحالة من أربع، ونص المصدر حرفيًا، والفرق بمواضع الحروف. الحروف لا تُعاد كتابتها أبدًا.",
  dev_mcp: "خادم MCP",
  dev_mcp_d: "أدوات مقترحة: check_text و check_image و list_sources و grounding_rules — بنفس مخرجات REST حرفيًا. لم يُنشر بعد.",
  dev_mcp_cfg: "إعداد العميل (مخطَّط، لا يعمل بعد)",
  dev_guards: "الضوابط",
  dev_guards_d: "حدّ للطلبات لكل عميل، وظرف أخطاء موحّد بالعربية والإنجليزية، ولا حفظ لأي مدخل.",
  dev_open_docs: "افتح التوثيق التفاعلي",
  copy: "نسخ",
  copied: "نُسخ",

  // trust
  trust_title: "لماذا تثق بنا",
  trust_sub: "لا نطلب ثقتك. نعرض ما قسناه، وكيف قسناه، وأين يتوقف.",
  trust_numbers: "الأرقام المقاسة",
  trust_numbers_d: "كل رقم هنا مولّد آليًا من تقرير في المستودع، مع اسم الملف والسطر. لا رقم مكتوب باليد.",
  trust_from: "المصدر",
  trust_n: "العيّنة",
  trust_ci: "فترة الثقة ٩٥٪",
  m_eval_pass: "حالات الاختبار الداخلية التي نجحت",
  m_eval_unsafe: "حالات أعطت حالة غير مسموحة",
  m_eval_recall: "نصوص حرفية وُجدت في موضعها المتوقَّع",
  m_eval_fa: "إنذار خاطئ على نصوص حرفية من المصادر",
  m_ie1b_acc: "دقة التحقق على مجموعة IslamicEval 2025 (تطوير)",
  m_ie1b_danger: "نصوص خاطئة قُبلت على أنها مطابقة",
  m_ie26_ayah: "دقة الآيات على IslamicEval 2026 (تطوير)",
  m_ie26_matn: "دقة متون الأحاديث على IslamicEval 2026 (تطوير)",
  m_ie1a_f1: "تحديد مواضع الاقتباس (F1) مع الذكاء الاصطناعي",
  trust_caveat:
    "حالات الاختبار الداخلية مولّدة من سجلات المصادر بتعديلات آلية؛ تقيس المحرك لا توزيع المنشورات الحقيقية. أرقام IslamicEval على مجموعة التطوير العامة لا مجموعة الاختبار المخفية.",
  trust_method: "المنهجية",
  meth_1_t: "مصادر مثبّتة",
  meth_1_d: "كل ملف مصدر يُنزّل ويُتحقق من بصمته sha256؛ أي اختلاف يوقف البناء.",
  meth_2_t: "مطابقة حتمية",
  meth_2_d: "التطبيع للفهرسة والمقارنة فقط. النص المعروض هو حقل المصدر بايتًا بايتًا.",
  meth_3_t: "آلة حالات بثوابت",
  meth_3_d: "قواعد مختبرة تمنع مثلًا أن تُعطى آية مختلفة حالة «وُجد».",
  meth_4_t: "مدقّق لاحق على كل رد",
  meth_4_d: "يتحقق أن النص المعروض مطابق للمصدر وأن كل مرجع موجود وأنه لا كلمة حكم في نصوصنا؛ وإلا تُحال النتيجة للمراجعة.",
  trust_sources: "المصادر",
  trust_sources_d: "تُقرأ هذه القائمة حيّة من الخادم.",
  trust_sources_offline: "تعذّر تحميل سجل المصادر من الخادم الآن.",
  limits_title: "حدودنا",
  limits_sub: "ما لا تغطيه بصيرة، معلنًا قبل أن تكتشفه.",
  limit_1: "القرآن برواية حفص عن عاصم فقط؛ الاختلاف الذي قد يكون قراءة أخرى يُحال للمراجعة ولا يُخطَّأ.",
  limit_2: "الأحاديث من الكتب التسعة وموسوعة الأحاديث النبوية؛ ما خارجها «لم يوجد في مصادرنا» وليس حكمًا عليه.",
  limit_3: "ترقيم الأحاديث هو ترقيم مجموعة Open-Hadith-Data الداخلي، لا ترقيم الطبعات المعتمدة.",
  limit_4: "لا نُقيّم الأحاديث. إن ظهر حكم فهو منقول حرفيًا من موسوعة الأحاديث النبوية ومنسوب إليها.",
  limit_5: "الاقتباس غير المحاط بعلامات قد يفوت المستخرج؛ الآيات تُغطّى بمسح حتمي إضافي، والأحاديث قيد معلن.",
  limit_6: "النص المقروء من صورة يُعرض لك دائمًا لتتأكد منه، ونتائجه تبقى «يحتاج مراجعة».",
  limit_7: "الحد الأقصى ٥٠٠٠ حرف للفحص الواحد.",
  limit_8: "بصيرة أداة مساعدة لا تُفتي ولا تغني عن أهل العلم.",

  // about
  about_title: "عن بصيرة",
  about_lead:
    "بصيرة تتحقق من أن الآية أو الحديث منقول بحرفه كما في المصدر قبل أن ينتشر. صُمّمت للمعرّفين بالإسلام والدعاة، لأن خطأً واحدًا في النقل يُضعف الرسالة كلها.",
  about_why_t: "لماذا الآن؟",
  about_why_d:
    "النماذج اللغوية تكتب بطلاقة، وقد تخطئ في النص الشرعي بطلاقة أيضًا. بصيرة لا تنافسها في الكتابة؛ بل تقف بين النص والنشر وتقول: هذا ما في المصدر حرفيًا.",
  about_challenge_t: "المسابقة",
  about_challenge_d: "مشاركة في تحدي الذكاء الاصطناعي في خدمة المحتوى الإسلامي 2026 — مؤسسة باذل بالتعاون مع سدايا. المسار الرابع: أدوات التحقق لتمكين المعرّفين بالإسلام.",
  about_principles_t: "مبادئ لا تتغير",
  about_ai_t: "الإفصاح عن الذكاء الاصطناعي",
  about_ai_d:
    "يُستخدم نموذج لغوي لتحديد مواضع الاقتباس في النص وقراءة الصور فقط. كل موضع يقترحه يُعاد تحديده حرفيًا داخل نصك، ولا يُعرض أي نص ديني من مخرجاته. تفاصيل الأدوات في AI_USAGE.md.",
  about_code: "الشيفرة المصدرية",

  // footer
  footer_tag: "بصيرة · Basira",
  footer_product: "المنصة",
  footer_trust: "الثقة",
  footer_api: "التوثيق التفاعلي",
  footer_limits: "حدودنا",
  footer_sources: "المصادر",

  // misc
  theme: "تبديل الوضع الليلي",
  lang: "English",
  health_ok: "المحرك جاهز",
  health_loading: "المحرك يحمّل المصادر…",
  health_down: "المحرك غير متاح",
  not_found_title: "هذه الصفحة غير موجودة",
  not_found_d: "ربما تغيّر الرابط.",
  back_home: "العودة للرئيسية",
  install: "ثبّت التطبيق",
};

type Keys = keyof typeof ar;

const en: Record<Keys, string> = {
  nav_home: "Home",
  nav_check: "Workspace",
  nav_services: "Services",
  nav_developers: "Developers",
  nav_trust: "Why trust us",
  nav_about: "About",
  nav_menu: "Menu",
  nav_close: "Close menu",
  nav_primary: "Primary navigation",
  cta_start: "Start checking",
  cta_try: "Try your text",
  skip: "Skip to content",
  badge_live: "Live",
  badge_soon: "Coming soon",
  badge_soon_long: "In development — not live yet",

  identity: "The trust layer for sacred text in the age of AI",
  motto_ai: "AI understands",
  motto_engine: "the engine verifies",

  hero_kicker: "Check before you publish",
  hero_title: "Before a text spreads, make sure it was quoted word for word.",
  hero_sub:
    "Paste a post or upload its image. Basira extracts every verse and hadith, matches it letter by letter against the source, and shows the source text next to yours with every difference highlighted.",
  hero_secondary: "How it works",
  demo_label: "Live demonstration of a post being checked",
  demo_caption_recorded: "Response recorded verbatim from the Basira engine for this post",
  demo_caption_live: "Live result from the engine, just now",
  demo_post_title: "A post, before it is published",
  demo_replay: "Replay",
  demo_run_live: "Run it live on the engine",
  demo_running: "Checking…",
  demo_your_word: "Yours",
  demo_source_word: "Source",
  demo_ai: "AI located the quotations",
  demo_engine: "Engine matched letter by letter",
  demo_ms: "{ms} ms",
  demo_quotes: "{n} quotations",
  demo_open: "Open this example in the workspace",
  demo_diff: "Difference",

  how_title: "Three steps. Every role is explicit.",
  how_sub: "AI never writes a single letter of sacred text. It only locates quotations; a deterministic engine then verifies every letter.",
  how_1_t: "You paste or upload",
  how_1_d: "A post, a message, a comment, or a screenshot. Up to 5,000 characters. Nothing is stored.",
  how_2_t: "AI understands",
  how_2_d: "It reads the text or image and marks where each verse and hadith starts and ends; every proposal is re-located verbatim inside your text.",
  how_3_t: "The engine verifies",
  how_3_d: "Deterministic matching against sources pinned by version and checksum: same text, same result, and the source shown exactly as it is.",
  how_role_ai: "AI's role",
  how_role_engine: "Engine's role",

  states_title: "Only four states. No verdicts.",
  states_sub: "Basira never passes a verdict on a text. It says where it found it in its sources, and how your text differs.",
  state_found_d: "Your text matches the source exactly. We show where, and the source text.",
  state_partial_match_d: "Very close to a hadith in our sources; the differing words are highlighted.",
  state_needs_review_d: "Any difference from the Mushaf text, or anything too thin to check automatically, goes to your review.",
  state_not_found_d: "A statement about our sources' coverage — not a judgment on the text.",

  services_title: "Services",
  services_sub: "What is live really runs on the engine. What is not built yet is labelled clearly.",
  svc_text_t: "Check Arabic text",
  svc_text_d: "Paste a whole post; every quotation is extracted and matched against the Mushaf and the nine hadith books.",
  svc_text_out: "You get: a state per quotation, the source text, the highlighted difference, and reference links.",
  svc_image_t: "Check an image",
  svc_image_d: "Upload a screenshot; the text is read automatically and shown to you to confirm before you rely on the result.",
  svc_image_out: "You get: the text read from the image, then the same text check.",
  svc_en_t: "Check an English quotation",
  svc_en_d: "Traces a translated quotation back to its Arabic original and shows the approved translation from QuranEnc and HadeethEnc.",
  svc_en_out: "You will get: the Arabic original from the source + the approved translation, attributed with its version.",
  svc_guard_t: "The Guard",
  svc_guard_d: "Check any Islamic chatbot's answer before trusting it: every verse and hadith in the answer goes through the engine.",
  svc_guard_out: "You will get: a report for every quotation in the model's answer.",
  svc_api_t: "REST API & MCP Server",
  svc_api_d: "The REST API is live. An MCP server so any AI assistant can check its quotations before showing them — in development.",
  svc_api_out: "You get: the same response the interface uses, as documented JSON.",
  svc_receipt_t: "Verification receipt",
  svc_receipt_d: "A fingerprint and QR code that reproduce the same result for anyone — without storing your text.",
  svc_receipt_out: "You will get: a link/code proving what was checked, when, and against which source versions.",
  svc_trust_t: "Why trust us",
  svc_trust_d: "Measured numbers, their method and sources, and an «Our limits» page with what we do not cover.",
  svc_trust_out: "Every number cited from the repository's reports.",
  svc_open: "Open",
  svc_learn: "Details",
  svc_for: "Who is it for?",
  svc_audience: "For people who introduce Islam, preachers, and anyone publishing religious content — in Arabic and English.",

  check_title: "Workspace",
  check_sub: "Paste text or upload an image. Results appear inside your own text.",
  mode_text: "Arabic text",
  mode_image: "Image",
  mode_en: "English quotation",
  mode_guard: "The Guard",
  modes_label: "Check type",
  pipe_title: "What happened in this check",
  pipe_ai: "AI",
  pipe_ai_d: "located the quotations",
  pipe_engine: "Deterministic engine",
  pipe_engine_d: "matched against the sources",
  pipe_validator: "Post-validator",
  pipe_validator_d: "responses rejected: {n}",
  pipe_corpus: "Source versions",
  pipe_degraded: "fixed rules only",
  receipt_soon: "Verification receipt (fingerprint + QR)",
  soon_panel_en: "This check is in development. We will not show a result for an English quotation until it really runs on the engine.",
  soon_panel_guard: "The Guard is in development. For now, paste the chatbot's answer into «Arabic text» to check the verses and hadiths in it.",
  go_text_mode: "Go to text check",

  dev_title: "Developers",
  dev_sub: "The same engine the interface uses, through a documented REST API. No key for public checks, with rate limiting.",
  dev_quick: "Start in a minute",
  dev_endpoints: "Endpoints available now",
  dev_method: "Method",
  dev_path: "Path",
  dev_what: "Purpose",
  ep_health: "Server readiness, corpus counts and versions",
  ep_check: "Check a text (up to 5,000 characters)",
  ep_image: "Check an image; also returns the text read",
  ep_sources: "Source register: version, licence, record count",
  ep_messages: "Every user-facing string",
  ep_docs: "Interactive documentation (OpenAPI)",
  dev_contract: "Response contract",
  dev_contract_d: "Every response carries the source versions, one of four states, the verbatim source text, and the diff as character offsets. Letters are never rewritten.",
  dev_mcp: "MCP server",
  dev_mcp_d: "Planned tools: check_text, check_image, list_sources, grounding_rules — byte-equal with REST output. Not published yet.",
  dev_mcp_cfg: "Client configuration (planned, not live)",
  dev_guards: "Guards",
  dev_guards_d: "Per-client rate limit, one bilingual error envelope, and no input is ever stored.",
  dev_open_docs: "Open interactive docs",
  copy: "Copy",
  copied: "Copied",

  trust_title: "Why trust us",
  trust_sub: "We don't ask for your trust. We show what we measured, how, and where it stops.",
  trust_numbers: "Measured numbers",
  trust_numbers_d: "Every number here is generated from a report in the repository, with file and line. None is typed by hand.",
  trust_from: "Source",
  trust_n: "Sample",
  trust_ci: "95% CI",
  m_eval_pass: "Internal test cases passed",
  m_eval_unsafe: "Cases that produced a disallowed state",
  m_eval_recall: "Verbatim texts found at the right place",
  m_eval_fa: "Spurious alarms on verbatim source text",
  m_ie1b_acc: "Verification accuracy, IslamicEval 2025 (dev)",
  m_ie1b_danger: "Wrong texts accepted as matching",
  m_ie26_ayah: "Verse accuracy, IslamicEval 2026 (dev)",
  m_ie26_matn: "Hadith text accuracy, IslamicEval 2026 (dev)",
  m_ie1a_f1: "Quotation location (F1) with AI",
  trust_caveat:
    "Internal cases are generated from source records with mechanical edits; they measure the engine, not real-world posts. IslamicEval numbers are on the public dev set, not the hidden test set.",
  trust_method: "Method",
  meth_1_t: "Pinned sources",
  meth_1_d: "Every source file is downloaded and its sha256 verified; any mismatch stops the build.",
  meth_2_t: "Deterministic matching",
  meth_2_d: "Normalisation is for indexing and comparison only. The displayed text is the source field, byte for byte.",
  meth_3_t: "A state machine with invariants",
  meth_3_d: "Tested rules that, for example, never give a differing verse the state «Found».",
  meth_4_t: "A post-validator on every response",
  meth_4_d: "Checks the displayed text equals the source, every reference exists, and none of our strings carries a verdict; otherwise the result goes to review.",
  trust_sources: "Sources",
  trust_sources_d: "This list is read live from the server.",
  trust_sources_offline: "The source register could not be loaded from the server right now.",
  limits_title: "Our limits",
  limits_sub: "What Basira does not cover — stated before you find out.",
  limit_1: "Quran in the Hafs ʿan ʿĀṣim reading only; a difference that may be another reading goes to review, never marked as an error.",
  limit_2: "Hadith from the nine books and the Prophetic Hadiths Encyclopedia; anything else is «not found in our sources», not a judgment.",
  limit_3: "Hadith numbers are the Open-Hadith-Data collection's internal numbering, not edition numbering.",
  limit_4: "We never grade hadith. Any grading shown is quoted verbatim from the encyclopedia and attributed to it.",
  limit_5: "Unmarked quotations can escape the extractor; verses are covered by an extra deterministic scan, hadith remain a stated limit.",
  limit_6: "Text read from an image is always shown to you to confirm, and its results stay «Needs review».",
  limit_7: "Up to 5,000 characters per check.",
  limit_8: "Basira is an aid. It issues no religious rulings and does not replace scholars.",

  about_title: "About Basira",
  about_lead:
    "Basira checks that a verse or hadith is quoted in its exact wording before it spreads. It is built for people who introduce Islam and for preachers, because one quoting slip weakens the whole message.",
  about_why_t: "Why now?",
  about_why_d:
    "Language models write fluently — and can misquote sacred text just as fluently. Basira doesn't compete with them at writing; it stands between the text and publishing, and says: this is what the source says, verbatim.",
  about_challenge_t: "The challenge",
  about_challenge_d: "An entry in the AI in Service of Islamic Content Challenge 2026 — Bathel Foundation with SDAIA. Track 4: verification tools empowering those who introduce Islam.",
  about_principles_t: "Principles that do not change",
  about_ai_t: "AI disclosure",
  about_ai_d:
    "A language model is used only to locate quotations in text and to read images. Every location it proposes is re-located verbatim inside your text, and no religious text from its output is ever shown. Tools are listed in AI_USAGE.md.",
  about_code: "Source code",

  footer_tag: "Basira · بصيرة",
  footer_product: "Platform",
  footer_trust: "Trust",
  footer_api: "Interactive docs",
  footer_limits: "Our limits",
  footer_sources: "Sources",

  theme: "Toggle dark mode",
  lang: "العربية",
  health_ok: "Engine ready",
  health_loading: "Engine loading sources…",
  health_down: "Engine unavailable",
  not_found_title: "This page does not exist",
  not_found_d: "The link may have changed.",
  back_home: "Back home",
  install: "Install app",
};

export const SITE: Record<Lang, Record<Keys, string>> = { ar, en };
export type SiteKey = Keys;

export function t(lang: Lang, key: SiteKey, vars: Record<string, string | number> = {}): string {
  return SITE[lang][key].replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}

export function numfmt(lang: Lang): Intl.NumberFormat {
  return new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en");
}
