#!/usr/bin/env python3
"""Build the UI's example texts from the repository's own test cases — no religious text is typed by hand.

Sources: `eval/cases.yaml` (materialized by `eval/materialize.py`, i.e. cut from the pinned corpus by
record ID + mechanical mutation) and `scripts/smoke.py` CASES (the canonical smoke texts).

Outputs (both under frontend/src/__generated__/):
  examples.json — the workspace's «try an example» list, each item with its provenance.
  hero.json     — the home-page demo: text + the VERBATIM response of POST /v1/check (only with --record URL).

Run:  backend/.venv/bin/python scripts/gen_examples.py [--record http://localhost:8000]
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))
from app.store import load_store  # noqa: E402
from eval.materialize import materialize  # noqa: E402
from smoke import CASES as SMOKE  # noqa: E402

OUT = ROOT / "frontend" / "src" / "__generated__"
QURAN_WRAP = "قال تعالى: ﴿{q}﴾"  # the wrapper used by eval cases A-001/A-016 (prose, not religious text)
HADITH_WRAP = "قال ﷺ: «{q}»"


def smoke_text(i: int) -> str:
    return str(SMOKE[i][0])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--record", help="API base URL; records hero.json from a live POST /v1/check")
    args = ap.parse_args()
    store = load_store(ROOT / "corpus" / "index")
    cases = {c["id"]: c for c in yaml.safe_load((ROOT / "eval" / "cases.yaml").read_text(encoding="utf-8"))}

    def case(cid: str) -> str:
        return materialize(store, cases[cid]).text

    examples = [
        {"key": "example_quran_ok", "icon": "quran", "text": case("A-016"), "provenance": "eval/cases.yaml A-016"},
        {"key": "example_quran_typo", "icon": "diff-words", "text": QURAN_WRAP.format(q=smoke_text(1)), "provenance": "scripts/smoke.py CASES[1] (adversarial typo)"},
        {"key": "example_hadith", "icon": "hadith", "text": case("E-067"), "provenance": "eval/cases.yaml E-067"},
        {"key": "example_hadith_variant", "icon": "state-partial", "text": case("F-075"), "provenance": "eval/cases.yaml F-075"},
    ]
    hero_lines = [
        "تذكير قبل النشر:",
        case("A-016"),
        "و" + case("F-075"),
        "و" + QURAN_WRAP.format(q=smoke_text(1)),
        "و" + HADITH_WRAP.format(q=smoke_text(7)),
    ]
    hero_text = "\n".join(hero_lines)
    examples.append({"key": "example_mixed", "icon": "paste-text", "text": hero_text, "provenance": "A-016 + F-075 + smoke[1] + smoke[7]"})
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "examples.json").write_text(
        json.dumps({"$comment": "GENERATED by scripts/gen_examples.py from eval/cases.yaml + scripts/smoke.py. Do not edit.", "items": examples}, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )
    print("examples.json:", len(examples), "items")
    if args.record:
        body = json.dumps({"text": hero_text, "ui_lang": "ar", "source_modality": "text", "options": {"max_candidates": 3}}).encode()
        req = urllib.request.Request(args.record.rstrip("/") + "/v1/check", data=body, headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=60) as r:  # noqa: S310 — local engine URL given by the operator
            resp = json.loads(r.read())
        for q in resp["quotes"]:
            assert hero_text[q["span"]["start"] : q["span"]["end"]] == q["quoted_text"], q["id"]
        states = sorted({q["status"] for q in resp["quotes"]})
        print("hero states:", states, "timings:", resp["timings_ms"], "provider:", resp["extraction_provider"])
        (OUT / "hero.json").write_text(
            json.dumps(
                {
                    "$comment": "GENERATED by scripts/gen_examples.py --record: the verbatim POST /v1/check response for `text`. Do not edit.",
                    "recorded_at": dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%MZ"),
                    "provenance": "A-016 + F-075 + smoke[1] + smoke[7]",
                    "text": hero_text,
                    "response": resp,
                },
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
