#!/usr/bin/env python3
"""Generate frontend/src/__generated__/trust.json from the repo's measured reports — never typed by hand.

Every figure keeps the exact report file + line it came from, and the raw table row, so the
«Why trust us» page can cite it and a vitest guard can re-check it against the file.
Run: python3 scripts/gen_trust.py   (stdlib only)
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "src" / "__generated__" / "trust.json"


def find(path: str, pattern: str) -> tuple[int, str, re.Match[str]]:
    lines = (ROOT / path).read_text(encoding="utf-8").splitlines()
    rx = re.compile(pattern)
    for i, line in enumerate(lines, 1):
        m = rx.search(line)
        if m:
            return i, line, m
    raise SystemExit(f"pattern not found in {path}: {pattern}")


def item(key: str, path: str, pattern: str, value: str, n: str | None = None, ci: str | None = None) -> dict[str, object]:
    line_no, line, m = find(path, pattern)
    g = m.groupdict()
    return {
        "key": key,
        "value": g[value],
        "n": g.get(n) if n else None,
        "ci": g.get(ci) if ci else None,
        "source": path,
        "line": line_no,
        "row": line.strip(),
    }


ITEMS = [
    item("eval_pass", "eval/REPORT.md", r"^\| pass rate \(all cases\) \| (?P<v>[\d.]+) \| (?P<n>\d+/\d+) \| (?P<ci>\[[^\]]+\])", "v", "n", "ci"),
    item("eval_unsafe", "eval/REPORT.md", r"^\| \*\*unsafe verdicts\*\*[^|]*\| (?P<v>[\d.]+) \| (?P<n>\d+/\d+) \| (?P<ci>\[[^\]]+\])", "v", "n", "ci"),
    item("eval_recall", "eval/REPORT.md", r"^\| recall@found \| (?P<v>[\d.]+) \| (?P<n>\d+/\d+) \| (?P<ci>\[[^\]]+\])", "v", "n", "ci"),
    item("eval_fa", "eval/REPORT.md", r"^\| \*\*false-alarm rate\*\*[^|]*\| (?P<v>[\d.]+) \| (?P<n>\d+/\d+) \| (?P<ci>\[[^\]]+\])", "v", "n", "ci"),
    item("ie1b_acc", "eval/islamiceval/REPORT_1B.md", r"^\| \*\*Basira \(deterministic core\)\*\* \| dev \| \*\*(?P<v>[\d.]+)\*\* \(95 % CI (?P<ci>[\d.–]+)\) \|[^|]*\|[^|]*\| (?P<n>\d+)", "v", "n", "ci"),
    item("ie1b_danger", "eval/islamiceval/REPORT_1B.md", r"\*\*Dangerous direction\*\*.*?\*\*(?P<v>\d+)\*\* of (?P<n>\d+) wrong spans", "v", "n"),
    item("ie26_ayah", "eval/islamiceval/REPORT_2026.md", r"^\| Ayah acc \(n=(?P<n>\d+)\) \| [\d.]+ \| \*\*(?P<v>[\d.]+)\*\*", "v", "n"),
    item("ie26_matn", "eval/islamiceval/REPORT_2026.md", r"^\| matn acc \(n=(?P<n>\d+)\) \| [\d.]+ \| (?P<v>[\d.]+)", "v", "n"),
    item("ie1a_f1", "eval/islamiceval/REPORT_1A.md", r"^\| \*\*Basira \(rules\+llm\)\*\* \| dev \| \*\*(?P<v>[\d.]+)\*\*", "v"),
]

if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = {"$comment": "GENERATED by scripts/gen_trust.py from the reports cited in each item. Do not edit.", "items": ITEMS}
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    for it in ITEMS:
        print(f"{it['key']:12} {it['value']:>8}  n={it['n']}  ci={it['ci']}  ← {it['source']}:{it['line']}")
